# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20161115_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='password',
            field=models.CharField(blank=True, max_length=4000),
        ),
    ]
